# Generated by Django 5.1.6 on 2025-02-19 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('type1', 'Type1'), ('type2', 'Type2')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
