# Generated by Django 5.1.6 on 2025-02-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_alter_product_product_type_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('type1', 'Type1'), ('type2', 'Type2'), ('type3', 'Type3')], default='type1', max_length=10),
        ),
    ]
